"""Reconciler-owned identity baseline (spec 02 D8'/D10).

reconcile/identity.yaml maps each project's stable kb_id -> {name, group} as of
the last reconcile. It is a deterministic filesystem snapshot of the live .kb-id
files (NOT derived from the LLM-written manifest/scout-cache). detect compares the
current live scan against this baseline; stamp/apply refresh it. The .kb-id files
remain the single source of truth.
"""
from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from tools.reconciler import idgen
from tools.reconciler.paths import dev_root
from tools.reconciler.vault import atomic_write, load_manifest

BASELINE_FILE = "reconcile/identity.yaml"
KNOWN_GROUPS = ("1.0-dev", "1.1-dev-tools", "2.0-career", "3.0-work", "5.0-home")

_HEADER = (
    "# reconcile/identity.yaml - reconciler-owned identity baseline (spec 02 D8'/D10).\n"
    "# kb_id -> {name, group} snapshot of live .kb-id files at the last reconcile.\n"
    "# GENERATED by `reconciler stamp` / `apply`; the .kb-id files are the source of truth.\n"
)


@dataclass
class LiveScan:
    live: dict[str, dict[str, str]] = field(default_factory=dict)    # kb_id -> {name, group, path}
    collisions: list[dict[str, Any]] = field(default_factory=list)   # {kb_id, repos: [...]}
    unstamped: list[str] = field(default_factory=list)               # "<group>/<dir>"


def _groups(vault: Path) -> set[str]:
    man_groups = {e["group"] for e in load_manifest(vault) if e.get("group")}
    return man_groups | set(KNOWN_GROUPS)


def scan_live(vault: Path) -> LiveScan:
    """Walk dev_root/<group>/* reading only .kb-id. Offline, deterministic."""
    root = dev_root()
    by_id: dict[str, list[dict[str, str]]] = defaultdict(list)
    scan = LiveScan()
    for group in sorted(_groups(vault)):
        gdir = root / group
        if not gdir.is_dir():
            continue
        for repo in sorted(p for p in gdir.iterdir()
                           if p.is_dir() and not p.name.startswith((".", "_"))):
            try:
                kid = idgen.read_kb_id(repo)
            except ValueError:
                scan.unstamped.append(f"{group}/{repo.name} (malformed .kb-id)")
                continue
            if kid is None:
                scan.unstamped.append(f"{group}/{repo.name}")
                continue
            by_id[kid].append({"name": repo.name, "group": group, "path": f"{group}/{repo.name}"})
    for kid, infos in by_id.items():
        if len(infos) > 1:
            scan.collisions.append({"kb_id": kid, "repos": [i["path"] for i in infos]})
        else:
            scan.live[kid] = infos[0]
    return scan


def load_baseline(vault: Path) -> dict[str, dict[str, str]]:
    """Read reconcile/identity.yaml. Returns {} for an absent OR corrupt file —
    the .kb-id files are the source of truth, so a hand-broken baseline must
    degrade gracefully, never crash a reconcile."""
    p = vault / BASELINE_FILE
    if not p.exists():
        return {}
    try:
        data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        return {k: {"name": v["name"], "group": v["group"]}
                for k, v in data.items() if isinstance(v, dict) and "name" in v and "group" in v}
    except (yaml.YAMLError, AttributeError, TypeError, OSError):
        return {}


def write_baseline(vault: Path, mapping: dict[str, dict[str, str]]) -> None:
    body = yaml.safe_dump(
        # sort_keys=False: deterministic order is enforced by sorted(mapping.items()) here.
        {k: {"name": v["name"], "group": v["group"]} for k, v in sorted(mapping.items())},
        sort_keys=False, default_flow_style=False, allow_unicode=True,
    )
    atomic_write(vault / BASELINE_FILE, _HEADER + body)


def refresh_baseline(vault: Path) -> dict[str, dict[str, str]]:
    """Snapshot current live state -> identity.yaml (drops collisions/unstamped).

    Fail-safe: if the live scan finds zero ids but a non-empty baseline already
    exists, preserve it (most likely dev_root is mispointed / repos absent) —
    never silently clobber a good baseline with an empty one.
    """
    scan = scan_live(vault)
    mapping = {kid: {"name": i["name"], "group": i["group"]} for kid, i in scan.live.items()}
    if not mapping:
        prior = load_baseline(vault)
        if prior:
            print("refresh_baseline: live scan returned 0 ids — prior baseline preserved "
                  "(is KB_DEV_ROOT correct?)")
            return prior
    write_baseline(vault, mapping)
    return mapping


def resolve_name(vault: Path, op: dict[str, Any], key: str = "name",
                 baseline: dict[str, dict[str, str]] | None = None) -> str | None:
    """Current/last-known slug for an op. Prefer op['id'] via the baseline; else op[key].
    Pass a pre-loaded `baseline` to avoid re-reading identity.yaml per op in a loop."""
    kid = op.get("id")
    if kid:
        if baseline is None:
            baseline = load_baseline(vault)
        entry = baseline.get(kid)
        if entry and entry.get("name"):
            return entry["name"]
    return op.get(key)
