/**
 * graph.ts -- build-time loader for the KB dependency graph.
 *
 * Reads <vault>/00-meta/graph.json (gitignored, regenerated by kb-sync).
 * Resolves path from KB_VAULT env var (same root used by content.config.ts).
 *
 * If the file is absent the loader returns an empty graph so the build
 * succeeds -- the page degrades gracefully.
 *
 * graph.json shape (from kb-sync):
 *   { nodes: [{ id, label, type, rag, group, topo_rank, cycle_id, goal, next, blocker }],
 *     edges: [{ s, d, t, cycle, brk }] }
 *   t in: requires | blocked | partof | supersedes | related | gates
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// --------------------------------------------------------------------------
// Types
// --------------------------------------------------------------------------

export type NodeRag = 'red' | 'yellow' | 'green' | null;

/** One entry in the blocked_by rollup emitted by kb-graph for objective nodes. */
export interface BlockedByEntry {
  node: string;       // graph node id of the blocking node
  text: string;       // human-readable blocker description
  distance: number;   // hop distance from the objective
}

export interface GraphNode {
  id: string;          // e.g. "02-projects/1.0-dev/ProjectOne.md"
  label: string;
  type: string | null;
  kind: string | null; // 'ultimate' | 'milestone' | null (objective nodes only)
  rag: NodeRag;
  group: string | null;
  topo_rank: number;
  cycle_id: string | null;
  goal: boolean;
  next: string | null;
  blocker: string | null;
  /** Rollup of nodes that transitively block this objective (emitted by kb-graph). */
  blocked_by?: BlockedByEntry[];
  /** IDs of objectives this node transitively blocks (emitted by kb-graph). */
  blocks_objectives?: string[];
  /** Primary language tag extracted by kb-sync (e.g. "python"); null when absent. */
  language?: string | null;
  /**
   * Dormant summary fields emitted by kb-sync -- present in graph.json for type-safety
   * only. The panel rendering path reads the content-collection copies via the enrich
   * map (NodeEnrichment) instead. Do NOT read these graph-node copies onto the detail
   * panel; the enrich map is the authoritative source for panel rendering.
   */
  nextstep0?: string | null;
  objective?: string | null;
  problem?: string | null;
  file?: string | null;
  adrs?: string[];
}

export type EdgeType = 'requires' | 'blocked' | 'partof' | 'supersedes' | 'related' | 'gates' | 'advances';

export interface GraphEdge {
  s: string;   // source node id
  d: string;   // destination node id
  t: EdgeType;
  cycle: boolean;
  brk: boolean; // true = this is the suggested break edge for a cycle
}

export interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

// --------------------------------------------------------------------------
// Normalisation: graph.json id -> Astro note.id (routable path)
// --------------------------------------------------------------------------
//
// Astro Content Layer glob loader transforms file paths:
//   - Strip .md extension
//   - Each path segment: strip dots, lowercase
// Examples:
//   "02-projects/1.0-dev/ProjectOne.md" -> "02-projects/10-dev/projectone"
//   "02-projects/1.1-dev-tools/ProjectTwo.md"  -> "02-projects/11-dev-tools/projecttwo"

export function graphIdToNoteId(graphId: string): string {
  return graphId
    .replace(/\.md$/, '')
    .split('/')
    .map((seg) => seg.replace(/\./g, '').toLowerCase())
    .join('/');
}

// --------------------------------------------------------------------------
// Load
// --------------------------------------------------------------------------

const VAULT = process.env.KB_VAULT ?? '..';
const GRAPH_PATH = join(VAULT, '00-meta', 'graph.json');

export function loadGraph(): GraphData {
  try {
    const raw = readFileSync(GRAPH_PATH, 'utf-8');
    const parsed = JSON.parse(raw) as GraphData;
    // Minimal defensive check
    if (!Array.isArray(parsed.nodes) || !Array.isArray(parsed.edges)) {
      console.warn('[graph.ts] graph.json missing nodes or edges arrays - using empty graph');
      return { nodes: [], edges: [] };
    }
    return parsed;
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`[graph.ts] graph.json not found or unreadable (${msg}) - dashboard will show empty graph`);
    return { nodes: [], edges: [] };
  }
}

// --------------------------------------------------------------------------
// Filter to a renderable subgraph
// --------------------------------------------------------------------------
//
// Default filter: type in {project, adr, goal, gate} for nodes, PLUS the
// structural backbone of type:moc group/tier nodes that link kept nodes into
// a connected hierarchy via partof edges.
//
// Backbone selection (two-pass, direction-aware):
//   graph.json partof edges run  moc -> project  (parent as source).
//   Pass 1: add any moc whose id is the SOURCE of a partof edge pointing at a
//           kept node. This pulls in the 5 group MOCs (01-groups/*.md).
//   Pass 2: add any moc whose id is the SOURCE of a partof edge pointing at a
//           pass-1 backbone moc (tier parents, if any). Currently yields 0
//           additions but is future-proof against a deeper hierarchy.
//
// 'related' edges hidden by default (hairball) but included in the data;
// the client can toggle them.

// ADRs are intentionally EXCLUDED from the default dependency graph: a single
// project can carry 30+ ADRs, each a partof-leaf, which turns the render into a
// hairball of star clusters and forces a tall vertical layout. ADRs remain
// browsable on the dedicated ADR page and per-project. The main graph shows the
// dependency backbone only: projects, goal nodes, and gates.
const DEFAULT_TYPES = new Set(['project', 'goal', 'gate', 'objective']);

export interface SubGraph {
  nodes: GraphNode[];
  edges: GraphEdge[];
  cycleCount: number;   // number of distinct cycle_ids
  openBlockerCount: number;  // nodes with blocker field set
  backboneCount: number; // number of structural backbone moc nodes added
}

// --------------------------------------------------------------------------
// Swim-lane (flagship) view
// --------------------------------------------------------------------------
//
// The Mission Control swim-lane layout is driven by operator-owned card fields
// (advances/phase), not by dagre topology. This filter therefore keeps the node
// TYPES that belong on the board -- project | objective | gate -- and drops the
// ~600 atomic notes (cli/error/adr) and the structural moc backbone + super-root
// used only for dagre connectivity. ALL projects are kept (every project gets a
// lane; unaligned ones land in the "Unaligned" lane) so the home page is
// all-information per the brief.
//
// Edges: keep only meaningful dependency edges (requires | blocked | advances |
// supersedes | gates) whose endpoints are both kept. The related(783)/partof(494)
// hairball is dropped for legibility. cycle/brk flags are preserved.

const LANE_TYPES = new Set(['project', 'objective', 'gate']);
const LANE_EDGE_TYPES = new Set<EdgeType>(['requires', 'blocked', 'advances', 'supersedes', 'gates']);

export function filterFlagshipGraph(graph: GraphData): SubGraph {
  const nodes = graph.nodes.filter((n) => n.type !== null && LANE_TYPES.has(n.type));
  const keptIds = new Set(nodes.map((n) => n.id));

  const edges = graph.edges.filter(
    (e) => LANE_EDGE_TYPES.has(e.t) && keptIds.has(e.s) && keptIds.has(e.d),
  );

  const cycleIds = new Set(nodes.map((n) => n.cycle_id).filter(Boolean));
  const openBlockerCount = nodes.filter((n) => n.blocker).length;

  return { nodes, edges, cycleCount: cycleIds.size, openBlockerCount, backboneCount: 0 };
}

export function filterGraph(
  graph: GraphData,
  types: Set<string> = DEFAULT_TYPES,
): SubGraph {
  // Step 1 -- primary kept set: {project, adr, goal, gate} + goal:true nodes
  const kept = graph.nodes.filter((n) => {
    if (!n.type) return false;
    if (n.goal) return true;
    return types.has(n.type);
  });

  let keptIds = new Set(kept.map((n) => n.id));

  // Step 2 -- backbone pass 1: moc nodes that are the SOURCE of a partof edge
  // whose DESTINATION is a kept node (i.e. group-level parent of a project/adr).
  const nodeById = new Map(graph.nodes.map((n) => [n.id, n]));
  const backboneIds = new Set<string>();

  for (const e of graph.edges) {
    if (e.t === 'partof' && keptIds.has(e.d)) {
      const src = nodeById.get(e.s);
      if (src?.type === 'moc') {
        backboneIds.add(e.s);
      }
    }
  }

  // Step 3 -- backbone pass 2: moc parents of the pass-1 backbone mocs
  // (handles a tier layer above the group mocs; currently yields 0 additions).
  const backboneIds2 = new Set<string>();
  for (const e of graph.edges) {
    if (e.t === 'partof' && backboneIds.has(e.d)) {
      const src = nodeById.get(e.s);
      if (src?.type === 'moc') {
        backboneIds2.add(e.s);
      }
    }
  }

  // Step 4 -- expand the kept id set with backbone nodes
  const backboneCount = new Set([...backboneIds, ...backboneIds2]).size;
  keptIds = new Set([...keptIds, ...backboneIds, ...backboneIds2]);

  // Step 5 -- recompute edges: both endpoints must be in the expanded set
  const edges = graph.edges.filter(
    (e) => keptIds.has(e.s) && keptIds.has(e.d),
  );

  // Step 6 -- drop degree-0 orphans so the DAG stays legible.
  // Gates and goal anchors are always shown (semantically important even when
  // isolated). Backbone moc nodes survive automatically because they carry at
  // least one partof edge in the kept set -- no special exemption needed.
  // The health strip and side panels read the full node set separately.
  const connected = new Set<string>();
  for (const e of edges) { connected.add(e.s); connected.add(e.d); }

  const allKeptNodes = graph.nodes.filter((n) => n.id && keptIds.has(n.id));
  const nodes = allKeptNodes.filter(
    (n) => connected.has(n.id) || n.type === 'gate' || n.type === 'goal' || n.type === 'objective' || n.goal,
  );

  // Count distinct non-null cycle_ids (over the rendered set)
  const cycleIds = new Set(nodes.map((n) => n.cycle_id).filter(Boolean));
  // openBlockerCount is over the original primary kept set (before backbone expansion)
  const openBlockerCount = kept.filter((n) => n.blocker).length;

  // Step 7 -- synthesize a single super-root so the graph is ONE connected
  // component. Without it, group clusters with no cross-group edge (e.g. the
  // career/home/work groups) render as separate components that cytoscape-dagre
  // stacks vertically -> a tall ribbon instead of a left-to-right tree. The root
  // links to each backbone group MOC actually rendered (root -> group MOC ->
  // project), so dagre lays the whole hierarchy out left-to-right. The root is
  // non-routable (graphIdToNoteId yields no matching note -> href null).
  const renderedIds = new Set(nodes.map((n) => n.id));
  const rootChildMocs = [...backboneIds, ...backboneIds2].filter((id) => renderedIds.has(id));
  if (rootChildMocs.length > 1) {
    const ROOT_ID = '__kb_root__';
    const rootNode: GraphNode = {
      id: ROOT_ID,
      label: 'Knowledge Base',
      type: 'moc',
      kind: null,
      rag: null,
      group: null,
      topo_rank: -1,
      cycle_id: null,
      goal: false,
      next: null,
      blocker: null,
    };
    const rootEdges: GraphEdge[] = rootChildMocs.map((mocId) => ({
      s: ROOT_ID,
      d: mocId,
      t: 'partof' as EdgeType,
      cycle: false,
      brk: false,
    }));
    return {
      nodes: [rootNode, ...nodes],
      edges: [...edges, ...rootEdges],
      cycleCount: cycleIds.size,
      openBlockerCount,
      backboneCount,
    };
  }

  return { nodes, edges, cycleCount: cycleIds.size, openBlockerCount, backboneCount };
}
